### ISSUE TITLE
Feature Request: Leverage Browser Caching

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#134]
[Google PageSpeed Insights Analysis](http://developers.google.com/speed/pagespeed/insights/) often recommends to site owners that they "leverage browser caching". 

> Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
> [Leverage browser caching](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching)

Several Quick Cache users have inquired about this and I think it would be a good idea to add this feature to Quick Cache Pro.

Requested here:
http://wordpress.org/support/topic/how-to-leverage-browser-caching-1
http://wordpress.org/support/topic/google-pagespeed-insights-suggests-leverage-browser-caching

---

Related: https://github.com/websharks/zencache/issues/255 https://github.com/websharks/zencache/issues/371 

---

### Next Actions

- [ ] Create a new method that can inject Browser Caching code into the root `.htaccess` file (this should be a universal method that can be used for inserting other code into `.htaccess` as well, such as GZIP Compression)
- [ ] Create a new ZenCache option to enable/disable Browser Caching
- [ ] Create a new Options Panel for Browser Caching; this should detect two things: 1) if web server is not Apache v2.1+ and show a notice indicating that Browser Caching is not supported, and 2) if root `.htaccess` is not writable, a notice should be displayed indicating as much and show the Browser Caching code that needs to be manually inserted into the root `.htaccess` file.
- [ ] On `admin_init` detect if Browser Caching option is enabled and Browser Caching code is not found in `.htaccess` file, it should display a warning
- [ ] A KB Article should be written that further explains Browser Caching and answers some frequently asked questions.
- [ ] Existing no-cache headers being enabled/disabled should be considered as part of this work. For instance, when browser caching is enabled via `.htaccess`, ZC should not send no-cache headers.
- [ ] Determine best practice for users running Nginx (i.e., what Nginx users should add to their config file to enable browser caching).
- [ ] Detect if user is running Nginx instead of Apache and show suggested config snippet to be added to their config file (requires root access, so user will need to handle that themselves).

**Comment by brunobatista** [comment]
+1 for this request.

**Comment by vaibhavmule** [comment]
+1

**Comment by lkraav** [comment]
What's the next step here?

**Comment by raamdev** [comment]
@lkraav Thanks for the ping. I added a list of Next Actions to the top of this GitHub Issue.

@jaswsinc When you get a chance, could you review the next actions I added just in case I missed anything. ↑

**Comment by jaswrks** [comment]
I added two more points to the bottom of the list above ↑

**Comment by isaumya** [comment]
Hey guys this is a great idea but there is one thing I should point about. You see the best part of ZenCache pro is that it is not server specific. So please try to keep that. I see that you guys have considered this for an apache server. But if you check the current server trend, most Webmasters who has their own vps uses ngix instead apache. But as in nginx there is no htaccess and you can't populate the vhost file without root access, I think you guys should try to detect if its a nginx server, in that case show the user the exact vhost code they need to use to achieve this feature. Thanks again for your great work.

**Comment by raamdev** [comment]
@isaumya Thank you for the feedback! :-) Yes, that's exactly what we plan to do with regards to Nginx--we'll come up with some best-practice suggestions and recommend those to users who we detect are running Nginx instead of Apache.

**Comment by isaumya** [comment]
@raamdev Thats good approach mate :)

**Comment by hamidpeya** [comment]
Hi everyone. I just past the basic code in my .htaccess file and it works perfectly but i was wondering 1week can be a long to cache.I tried to reduce the period but it seems Google don't like it more less than 1 week :) . But now my question is, Is it also effect the Adsense ads? Advance thanks to you guys :)

**Comment by raamdev** [comment]
@hamidpeya The AdSense JavaScript is not hosted on your server but rather is loaded from Google's servers, so the Leverage Browser Caching settings that you apply to your `.htaccess` file have no effect on the AdSense JavaScript.

**Comment by AskKim** [comment]
I was just pestering support about this for ZenCache Pro and discovered it oddly wasn't included. Hopefully it will be rolled out soon.

**Comment by raamdev** [comment]
Noting that work on this feature has started in https://github.com/websharks/comet-cache/issues/765.

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#134).
