### ISSUE TITLE
Feature Request: Automatic Pro Plugin Updates

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#289]
ZenCache Pro currently has a Plugin Updater that allows the plugin to be updated through the WordPress Dashboard, but it would be really nice if there was an option for site owners to enable _automatic_ plugin updates, thereby avoiding the need to manually update by clicking the update link.

This would work similar to the [Advanced Automatic Updates](http://wordpress.org/plugins/automatic-updater/) plugin that allows you to automatically keep WordPress plugins up-to-date.

---

Related: https://github.com/websharks/zencache/issues/395 https://github.com/websharks/zencache/issues/394 https://github.com/websharks/zencache/issues/465 https://github.com/websharks/zencache/issues/289 https://github.com/websharks/zencache/issues/464 https://github.com/websharks/zencache/issues/352 https://github.com/websharks/zencache/issues/477

**Comment by raamdev** [comment]
After the work done in https://github.com/websharks/comet-cache-pro/pull/272 that switched the custom Pro Updater system to the built-in WordPress Plugin Update system, I tried enabling Automatic Plugin and Theme Updates as per the WordPress Codex by adding this filter to an MU-Plugin:

```
add_filter( 'auto_update_plugin', '__return_true' );
add_filter( 'auto_update_theme', '__return_true' );
```

I had 1 theme that needed an update, and 1 plugin (Comet Cache Pro). The theme was updated automatically, but Comet Cache Pro was not, which means there must be something about the built-in Automatic Plugin Updates system that Comet Cache Pro isn't yet compatible with.

**Comment by jaswrks** [comment]
I just did a quick review of the routines associated with these filters and every indication that I've seen so far would suggest that this should work given the current Comet Cache dev branch. I will run some tests as well and report back.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Enhancement** (Pro): Comet Cache Pro is now fully compatible with [WordPress Automatic Background Updates](https://codex.wordpress.org/Configuring_Automatic_Background_Updates#Plugin_.26_Theme_Updates_via_Filter). If you enable automatic background updates for plugins, and you save valid Comet Cache Pro License Credentials in the _Comet Cache Pro → Plugin Options → Update Credentials_ panel, you will automatically receive Pro plugin updates. Props @jaswsinc. See [Issue #289](https://github.com/websharks/comet-cache/issues/289).

**Comment by raamdev** [comment]
**Comet Cache v160917** has been released and includes changes from this GitHub Issue. See the [v160917 announcement](https://cometcache.com/blog/comet-cache-v160917-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#289).
