### ISSUE TITLE
Note when Auto-Cache Engine generates cache file

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#292]
When the Auto-Cache Engine generates a cache file, it would be nice to include mention of that fact in the HTML notes that appear at the bottom of the cache file. At the very least, this would help when checking if the Auto-Cache Engine is working as expected. 

As of now, it's not possible to tell if the Auto-Cache Engine generated the cache file, or if a regular visit to the site generated the cache file.

**Comment by jaswrks** [comment]
The Auto-Cache sets a User-Agent string of `zencache`, which makes it possible for the [is_auto_cache_engine()](https://github.com/websharks/zencache-pro/blob/000000-dev/zencache-pro/includes/share.php#L843) method to work as expected.

So to implement this a note can be added whenever `is_auto_cache_engine()` is `TRUE`.

See: https://github.com/websharks/zencache/blob/000000-dev/zencache/includes/advanced-cache.tpl.php#L944

**Comment by raamdev** [comment]
@jaswsinc Thanks for noting what needs to be done here! I'm marking this as `ready for work`.

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch for this issue.
- Replace [these lines](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Ac/ObUtils.php#L343-L348) with the following:
  
  ``` php
  if (COMET_CACHE_DEBUGGING_ENABLE && $this->isHtmlXmlDoc($cache)) {
      $total_time = number_format(microtime(true) - $this->timer, 5, '.', ''); // Based on the original timer.
      $via = IS_PRO && $this->isAutoCacheEngine() ? __('Auto-Cache Engine', SLUG_TD) : __('HTTP request', SLUG_TD);
      $cache .= "\n".'<!-- '.htmlspecialchars(sprintf(__('%1$s file path: %2$s', SLUG_TD), NAME, str_replace(WP_CONTENT_DIR, '', $this->is_404 ? $this->cache_file_404 : $this->cache_file))).' -->';
      $cache .= "\n".'<!-- '.htmlspecialchars(sprintf(__('%1$s file built for (%2$s%3$s) in %4$s seconds, on: %5$s; via %6$s.', SLUG_TD), NAME, $this->is_404 ? '404 [error document]' : $this->salt_location, (IS_PRO && COMET_CACHE_WHEN_LOGGED_IN && $this->user_token ? '; '.sprintf(__('user token: %1$s', SLUG_TD), $this->user_token) : ''), $total_time, date('M jS, Y @ g:i a T'), $via)).' -->';
      $cache .= "\n".'<!-- '.htmlspecialchars(sprintf(__('This %1$s file will auto-expire (and be rebuilt) on: %2$s (based on your configured expiration time).', SLUG_TD), NAME, date('M jS, Y @ g:i a T', strtotime('+'.COMET_CACHE_MAX_AGE)))).' -->';
  }
  ```
- Test to be sure this works as expected.
- Submit PR for review.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Enhancement** (Pro): The HTML Notes added to the bottom of a cached page now specify if the page was cached as the result of an HTTP Request or if it was cached by the Auto-Cache Engine. Props @kristineds. See [Issue #292](https://github.com/websharks/comet-cache/issues/292).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#292).
