### ISSUE TITLE
Purge Author Page cache when user is deleted

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#304]
When a user is deleted in WordPress, the Author Page cache for that user, if one exists, should be purged. This can probably happen by attaching to the `delete_user` hook.

Forked from #297.

**Comment by jaswrks** [comment]
_Noting the [`remove_user_from_blog`](https://developer.wordpress.org/reference/functions/remove_user_from_blog/) hook as well, for Multisite compat._

**Comment by renzms** [comment]
@raamdev 

### Confirmed Working

After generating Author Cache, when deleting user/author, cache is cleared.

Tested in two cases where content would be redistributed and accredited to a new author, and another case where content along with the user/author would be deleted. Both cases cleared the author cache.


**Front End Cache Notes**
![screen shot 2016-12-15 at 7 59 47 pm](https://cloud.githubusercontent.com/assets/13220018/21223702/8eb53c30-c303-11e6-81e2-8d6e16b0b90e.png)


**Author Cache Created (FTP View)**
![screen shot 2016-12-15 at 8 13 00 pm](https://cloud.githubusercontent.com/assets/13220018/21223697/8ba80b26-c303-11e6-84b7-4da736fcbb85.png)



![screen shot 2016-12-15 at 8 13 41 pm](https://cloud.githubusercontent.com/assets/13220018/21223695/8a3d170e-c303-11e6-8c28-c66273913645.png)

**User Deleted and Cache Cleared (FTP View)**

![screen shot 2016-12-15 at 8 15 36 pm](https://cloud.githubusercontent.com/assets/13220018/21223694/88be4182-c303-11e6-80d7-a98623520221.png)

**User Deleted and Cache Cleared (Dashboard)**

![screen shot 2016-12-15 at 8 17 29 pm](https://cloud.githubusercontent.com/assets/13220018/21223689/87b5a140-c303-11e6-9d45-7f1f20429ffb.png)

**Comment by raamdev** [comment]
**Comet Cache v161221** has been released and includes changes from this GitHub Issue. See the [v161221 announcement](https://cometcache.com/blog/comet-cache-v161221-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#304).
