### ISSUE TITLE
Improve WordPress Multilingual Plugin (WPML) Compatibility

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#382]
There appears to be a few issues with Quick Cache and the WPML plugin, namely that when caching for logged-in users is enabled, the logged-in user cache gets purged immediately after it's created.

Related to #91.

Issue reported in https://websharks.zendesk.com/agent/tickets/4523
---

Steps to recreate this issue as reported by user:

> Quick Cache enable + Cache Login User ( separate files) enable + WPML enable 
> The cache works great for logout users 
> The cache for login user doesn't work as expected 
> -The cache for login users is created ( confirmed with note in the source code ) 
> -The cache for login users is instantly deleted ( Notification on the dashboard : Modification found .... chase user ID 345 cache cleared)
> 
> It seems that WPML is triggering a change and Quick Cache delete the cache just after creating it. 
---

WPML is not a free plugin, but it's popular enough that we should work towards improving compatibility with it. WPML has a [compatible plugins page](http://wpml.org/documentation/plugins-compatibility/) that we should work to get listed on via their [GoGlobal](http://wpml.org/documentation/theme-compatibility/go-global-program/) program, which will also give us access to WPML for testing.

**Comment by raamdev** [comment]
Referencing WPML's "GoGlobal" program, which certifies plugins and themes as compatible with WPML: http://wpml.org/documentation/theme-compatibility/go-global-program/

**Comment by jaswrks** [comment]
+1 for this. Referencing internal ticket: https://websharks.zendesk.com/agent/tickets/6093

**Comment by Reedyseth** [comment]
> WPML has a compatible plugins page that we should work to get listed on via their GoGlobal program, which will also give us access to WPML for testing.

@raamdev A long time ago a woman Called Rosario contacted me to add the StCR to WPML, I don't know if you remember. If you like so, I could give you here email address so that you can request the addition of Comment Cache.

**Comment by raamdev** [comment]
> Comment Cache.

You mean **Comet** Cache, right?

---

There's a related GitHub issue open for Comment Mail: https://github.com/websharks/comment-mail/issues/252

Also, it appears that we can add a WPML configuration file to the plugin to improve compatibility, but I need to research this a bit more: https://wpml.org/documentation/support/language-configuration-files/

**Comment by Reedyseth** [comment]
> You mean Comet Cache, right?

Correct :smile_cat: 

> There's a related GitHub issue open for Comment Mail

I am also taking noticed on that :+1: 

> Also, it appears that we can add a WPML configuration file to the plugin to improve compatibility, but I need to research this a bit more: https://wpml.org/documentation/support/language-configuration-files/

Yes, The first time that I did that just by adding the file was enough, then as per request as in #252 a few tweaks were needed.

**Comment by raamdev** [comment]
> then as per request as in #252 a few tweaks were needed.

#252 is a Comet Cache issue... did you mean something else?

**Comment by renzms** [comment]
@raamdev 

Have we previously applied for the [Go Global](https://wpml.org/documentation/theme-compatibility/go-global-program/) Program to have them test as well or to request a free copy for our testing?

**Comment by raamdev** [comment]
@renzms No, we have not applied. We need to do that.

**Comment by renzms** [comment]
@raamdev 

Ok, noted. I just applied for the Go Global program. Awaiting their email regarding the next steps. 👍

**Comment by renzms** [comment]
@raamdev 

**Update:**

They have given us a test site with WPML installed and Comet Cache for testing. Sent details to you on Slack.

**Comment by renzms** [comment]
@raamdev 

## Status

**Cannot reproduce issue.** 
Comet Cache Pro, with Logged In User Caching and Automatic Cache Clearing Enabled + WPML = Working as intended.

I've tested the issue along with a dev/tester of WPML in the test installation they've created for us and can confirm everything is working as it should be.

## Steps Taken to test issue
- enabled Comet Cache Pro and Logged-In User Caching
- enabled WPML and enabled configurations for Spanish translation
- disabled WP-Admin bar while logged in on Front-End pages via Comet Cache Logged-In User Caching panel
- a Cache was generated for Logged-In users for both the WPML Dev and I
- Verified the cache for both original and translated versions via the HTML snippet that is added in the source code
- Switched back and forth between English/Spanish and visited other pages on the site to verify the Logged In User cache is not being auto-cleared by WPML
- Tested the auto clear cache ability by updating the page on the backend. Automatic Cache Clearing working as intended and clears both original and translated cache for Logged-In Users

The page caches per user ID and creates a separate cache for the original version and the translated version upon first visit. The cache is not cleared for either unless manually cleared or an update is detected on the original page. Any backend update will clear the cache as intended as long as **Automatic Cache Clearing** is enabled.

All looks good on my end.

**Comment by raamdev** [comment]
@renzms Thanks for the testing! I'll go ahead mark this issue as closed.
