### ISSUE TITLE
InfiniteWP Support

### ISSUE THREAD

**Issue by jaswsinc** [websharks/comet-cache#394]
A customer writes...

> I use InfiniteWP to manage all my WordPress Installs. IWP checks if the plugins need updating and lets you update all your plugins of all your pages with a single click. QuickCache does not update, I believe, because it needs your username and password. Is there any way to fix this? Is this something the IWP people can fix?

Referencing: https://websharks.zendesk.com/agent/tickets/4759

---

Related: https://github.com/websharks/zencache/issues/395 https://github.com/websharks/zencache/issues/394 https://github.com/websharks/zencache/issues/465 https://github.com/websharks/zencache/issues/289 https://github.com/websharks/zencache/issues/464 https://github.com/websharks/zencache/issues/352

**Comment by colourstone** [comment]
I would love to see this also!! Thank you for the heads up via email Raam! please keep me informed. It's such a pain to go to each site individually and update.

Thank you!
Brent

**Comment by raamdev** [comment]
After the work that was done in https://github.com/websharks/comet-cache-pro/pull/272 to migrate the Comet Cache Pro Plugin Updater over to the built-in WordPress Plugin Updater, I tried testing a plugin update via InfiniteWP and while the Comet Cache Pro update shows up in InfiniteWP now, updating from the InfiniteWP Dashboard unfortunately still doesn't work:

![2016-09-02_17-03-06](https://cloud.githubusercontent.com/assets/53005/18218735/e34c8690-7132-11e6-9892-329e449bb49c.png)
![2016-09-02_17-23-46](https://cloud.githubusercontent.com/assets/53005/18218737/e52a28aa-7132-11e6-847d-f4fed50f956e.png)
![2016-09-02_17-28-25](https://cloud.githubusercontent.com/assets/53005/18218738/e6b5b2ac-7132-11e6-8bea-15ad053fb13f.png)
![2016-09-02_17-25-22](https://cloud.githubusercontent.com/assets/53005/18218739/e81abf2a-7132-11e6-8ea6-db70ddc2a0db.png)

The "Return to WordPress Updates page" as the response seems like a clue. 

Note that unlike ManageWP (which now [works great](https://github.com/websharks/comet-cache/issues/465#issuecomment-244485539) for remote Comet Cache Pro updates), InfiniteWP is a self-hosted solution that can be downloaded [here](https://infinitewp.com/). It uses the [InfiniteWP Client](https://wordpress.org/plugins/iwp-client/) plugin on the WordPress site to communicate between the self-hosted InfiniteWP Dashboard and the WordPress site. 

We'll need to do some more testing to get Comet Cache Pro updates compatible with InfiniteWP.

**Comment by jaswrks** [comment]
@raamdev Did you test this in standard WP or multisite?
Referencing: https://github.com/wp-plugins/iwp-client/blob/1.4.2.2/helper.class.php#L191

Also referencing [this filter](https://github.com/wp-plugins/iwp-client/blob/1.4.2.2/helper.class.php#L210), which is what CC is attaching to.

**Comment by raamdev** [comment]
> Did you test this in standard WP or multisite?

Standard.

**Comment by raamdev** [comment]
Noting also that I tested all of this locally. InfiniteWP was installed on my local Vagrant box, which was the same box the WordPress installation was located. I have not tried testing this on an internet-accessible site.

**Comment by jaswrks** [comment]
Copy that. I tracked down that error message, but I'm not sure how helpful that will be. It seems that it's actually coming from the WP core. https://github.com/WordPress/WordPress/blob/a13164355f15612fa3d4a4367b4b216cc5bafc3f/wp-admin/includes/class-bulk-theme-upgrader-skin.php#L50

I haven't had the chance to test this myself yet. Do you have a screenshot of what is shown by that software when an update is successful?

**Comment by raamdev** [comment]
Here's what I get when everything gets updated successfully: 
![2016-09-08_18-37-35](https://cloud.githubusercontent.com/assets/53005/18369369/542d4808-75f3-11e6-8626-096eb6c02a97.png)

**Comment by raamdev** [comment]
@jaswsinc I just ran this through another test and it seems to be working as expected now... I'm not doing anything different or testing from anywhere new, so I have no explanation for why it's working now.

**Comment by jaswrks** [comment]
Nice! I'm adding it to my list to test with also. I haven't used this service at all yet.

**Comment by raamdev** [comment]
@jaswsinc Awesome. If I can get one more confirmation that this is working now, I'll close this and get a changelog added to the current release (currently in the RC phase).

The easiest way I found to test this was to build the `dev` branch, or even better the `release/160908-RC` branch, with `phing -D project_version=160701 full-build-all`, that way the v160709 update is detected and you can test upgrading via InfiniteWP.

**Comment by jaswrks** [comment]
I just ran some tests with this. It's working. However, it fooled me once or twice, because there are some PHP notices that seem to cause the sort of unexpected output buffer contents like you posted before. The first time or two I got this.

![2016-09-08_18-07-19](https://cloud.githubusercontent.com/assets/1563559/18373355/f22b238a-75ef-11e6-8710-7439c368fbd0.png)
![2016-09-08_18-07-59](https://cloud.githubusercontent.com/assets/1563559/18373356/f22c7460-75ef-11e6-8a24-e7582d21d819.png)

`wp-content/debug.log` shows...

```
[09-Sep-2016 02:02:20 UTC] PHP Notice:  Undefined index: activities_log_datetime in /app/src/wp-content/plugins/iwp-client/init.php on line 124
[09-Sep-2016 02:02:20 UTC] PHP Stack trace:
[09-Sep-2016 02:02:20 UTC] PHP   1. {main}() /app/src/wp-admin/index.php:0
[09-Sep-2016 02:02:20 UTC] PHP   2. require_once() /app/src/wp-admin/index.php:10
[09-Sep-2016 02:02:20 UTC] PHP   3. require_once() /app/src/wp-admin/admin.php:31
[09-Sep-2016 02:02:20 UTC] PHP   4. require_once() /app/src/wp-load.php:39
[09-Sep-2016 02:02:20 UTC] PHP   5. require_once() /app/src/wp-config.php:37
[09-Sep-2016 02:02:20 UTC] PHP   6. do_action() /app/src/wp-settings.php:358
[09-Sep-2016 02:02:20 UTC] PHP   7. iwp_mmb_parse_request() /app/src/wp-includes/plugin.php:524
```

---

When I take my test installation out of `WP_DEBUG` mode it works fine.

![2016-09-08_18-12-18](https://cloud.githubusercontent.com/assets/1563559/18373382/1bbe0ce4-75f0-11e6-8840-ea5e031b3051.png)

**Comment by raamdev** [comment]
@jaswsinc Ah, I see. That's helpful. So that looks like an InfiniteWP issue. Otherwise, the Comet Cache Pro Updater integration works fine with InfiniteWP and this can be marked as fixed, correct?

**Comment by jaswrks** [comment]
Correct. It seems to be working just fine under normal operating conditions.

**Comment by raamdev** [comment]
Next Release Changelog: 
- **InfiniteWP Compatibility** (Pro): Comet Cache Pro is now compatible with InfiniteWP, an application that allows you to manage multiple WordPress sites from a single location. Comet Cache Pro Plugin Updates will now appear in the InfiniteWP dashboard and, assuming you have saved valid license credentials in _Dashboard → Comet Cache Pro → Plugin Options → Update Credentials_, you will be able to upgrade Comet Cache Pro remotely from the InfiniteWP Dashboard. See [Issue #394](https://github.com/websharks/comet-cache/issues/394).

**Comment by raamdev** [comment]
**Comet Cache v160917** has been released and includes changes from this GitHub Issue. See the [v160917 announcement](https://cometcache.com/blog/comet-cache-v160917-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#394).
