### ISSUE TITLE
Test Image Uploads when using a Custom Attachment Taxonomies

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#399]
Referencing https://wordpress.org/support/topic/trying-to-get-property-of-non-object-in-error-when-uploading-media

---

The report claims that when the following taxonomy is registered:

``` php
add_action('init', 'test_attachment_taxonomy');

function test_attachment_taxonomy()
{
    register_taxonomy(
        'test_media_cat',
        'attachment',
        array(
            'public' => true,
            'show_admin_column' => 1,
            'show_in_nav_menus' => 1,
            'hierarchical' => 1,
            'update_count_callback' => '_update_generic_term_count',
            'sort' => 0,
            'rewrite' => array( 'slug' => 'test_media_cat' )
        )
    );
}
```

And when Quick Cache is active, and an image is uploaded via the WordPress Media Library, the following notices are generated and the image is not uploaded:

```
Notice: Trying to get property of non-object in /Users/adamboother/sites/isis-wp/wp-content/plugins/quick-cache-pro/quick-cache-pro.inc.php on line 2343

Notice: Trying to get property of non-object in /Users/adamboother/sites/isis-wp/wp-content/plugins/quick-cache-pro/quick-cache-pro.inc.php on line 2345

Notice: Trying to get property of non-object in /Users/adamboother/sites/isis-wp/wp-content/plugins/quick-cache-pro/quick-cache-pro.inc.php on line 2347

Notice: Trying to get property of non-object in /Users/adamboother/sites/isis-wp/wp-content/plugins/quick-cache-pro/quick-cache-pro.inc.php on line 2347
7673
```

---

I tested this once, and was unable to reproduce this problem, but it needs further testing before being marked as invalid. The [original support thread](https://wordpress.org/support/topic/trying-to-get-property-of-non-object-in-error-when-uploading-media) should also be updated with the outcome of this issue when it gets closed.

Note that this was originally tested with Quick Cache v141001.

**Comment by renzms** [comment]
@raamdev 

### Unable to reproduce issue

Followed directions by adding Custom Attachment taxonomy and uploaded an image via WP Media Library.

No problems with upload.

Tested using:

WordPress Version: 4.7
Current WordPress Theme: Twenty Sixteen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentysixteen/
Active Plugins: Comet Cache Pro v161227
PHP Version: 7.0.10-2+deb.sury.org~xenial+1
MySQL Version: 10.0.28-MariaDB-0ubuntu0.16.04.1

**Comment by raamdev** [comment]
Thanks, Renz. I'll go ahead and close this as `cannot reproduce`.
