### ISSUE TITLE
Cache is not automatically cleared when widgets are changed

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache#411]
### Steps to reproduce this bug
1. Install and activate Quick Cache (tested with v150129) leaving the deafult settings
2. Make sure at least one widget is being used (Dashboard → Appearance → Widgets)
3. Logout and visit the site to cache a page where the widget appears (so that the widget content is cached)
4. Now log back into the Dashboard and change (edit, delete, add) a widget that you know has been cached
#### Expected Behavior

The entire cache should be cleared, since a change to widgets may affect many pages on the site.
#### Observed Behavior

No cache files are cleared. The old cache file continues to be presented to users and the changes to widgets are not seen until the cache is cleared manually.

---
#### Support threads referencing this issue
- https://websharks.zendesk.com/agent/tickets/5051
- https://wordpress.org/support/topic/cache-not-cleared-when-widgets-are-chnagednew-widgets-are-added

---
## What Needs to Happen Here?
- [x] We need to attach to at least one new hook/filter in WordPress. I'm referencing [this filter](https://github.com/WordPress/WordPress/blob/master/wp-includes/widgets.php#L407) that we could attach to in order to automatically clear the cache whenever any widget is updated or removed.
- [x] We need to look at the difference between "removing" a widget and "deleting" a widget, and then see if the filter I mentioned will cover both cases. I think that it will not.
- [x] Determine next actions.

**Comment by rudrastays** [comment]
Hi,
Sorry for a late response. Ok so this indeed is a bug. I am not well versed with the programming/coding stuff. So I will be of little help. At the same time, I am sure we will have an updated patch addressing this minor issue soon...

**Comment by raamdev** [comment]
@rudrastays No worries on the late response. :-) If you'd like to help us test the fix when it's ready, I suggest joining the beta mailing list so that you are notified when the beta version is available to test: please sign-up to be a beta tester [here](http://www.websharks-inc.com/r/quick-cache-beta-testers-list/).

**Comment by jaswrks** [comment]
Referencing [this filter](https://github.com/WordPress/WordPress/blob/master/wp-includes/widgets.php#L407) that we could attach to in order to automatically clear the cache whenever any widget is updated or removed.

**Comment by raamdev** [comment]
@jaswsinc Thank you. I'm adding this to the Next Release milestone.

**Comment by jaswrks** [comment]
I'm adding a list of things (↑ above) that need to occur.

**Comment by raamdev** [comment]
@jaswsinc writes...

> Referencing this filter that we could attach to in order to automatically clear the cache whenever any widget is updated or removed.

It looks like you didn't reference a tagged version of that file, so the link is broken now. Were you referring to [`wp_unregister_sidebar_widget`](https://github.com/WordPress/WordPress/blob/4.6/wp-includes/widgets.php#L439)?

**Comment by jaswrks** [comment]
Yes, and there are two:
- [`wp_register_sidebar_widget`](https://github.com/WordPress/WordPress/blob/4.6/wp-includes/widgets.php#L371)
- [`wp_unregister_sidebar_widget`](https://github.com/WordPress/WordPress/blob/4.6/wp-includes/widgets.php#L439)

_**Note:** Both untested; i.e., I've never attached to either of these before._

**Comment by jaswrks** [comment]
Noting that the two hooks I referenced prior did not work out at all. Instead, I attached to `update_option_sidebars_widgets` via `update_option()`, which works great in my tests.

**Comment by renzms** [comment]
@raamdev @jaswsinc 

### Confirmed Working

Tested by removing, deleting, and updating/saving widgets and cache is cleared. A new cache is generated upon visiting the page where the widget was.


**Before:**
_______
>![screen shot 2016-12-15 at 12 35 54 pm](https://cloud.githubusercontent.com/assets/13220018/21211975/3b27c190-c2c3-11e6-8e4b-a2352ba08891.png)

**After:**
______
>![screen shot 2016-12-15 at 12 36 50 pm](https://cloud.githubusercontent.com/assets/13220018/21211973/3a560bd2-c2c3-11e6-9493-d246adce81f2.png)

**Comment by raamdev** [comment]
**Comet Cache v161221** has been released and includes changes from this GitHub Issue. See the [v161221 announcement](https://cometcache.com/blog/comet-cache-v161221-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#411).
